### ISSUE TITLE
Modified Rebuilt ISO not working

### ISSUE THREAD

**Issue by RockSaltWA** [luckytyphlosion/auto-tt-recorder#1]
Heyo, 

I wanted to make a video for my music pack using Auto TT recorder. To do this I extracted my ripped ISO using WiiBaFu, replaced the audio files with mine, then rebuilt the ISO. After this, I redirected the config.yml to the new ISO and whenever it tries to record the run I get sent to the Wifi page and get error code. CMD doesn't throw any errors, 

What I suspect is happening is that the load time increases due to the increased file sizes of the music, so when the dolphin script is told to wait for the menu following the license screen to load it eats an "A" input. This results in the down input afterwards that was originally supposed to take the game into Time Trial mode to actually load the wifi selection. I was hoping that you would be able to direct me as to where I could change the script such that I could delay the setup ever so slightly so the game doesn't eat that A input so to speak. Would that be possible without recompiling? I assume it's just a script in dolphin but I'm not very tech savvy so any help would be amazing!

Thank you, 

Echo

**Comment by RockSaltWA** [comment]
Found a fix. Opened the dolphin lua script and edited local "advanceToCharacterSelectSegment" on line 344. 
``local advanceToCharacterSelectSegment = {
	{"none", 70},
	{"A", 230},
	{"A", 50},
	{"A", 75},
	{"A", 400},
	{"down", 25},
	{"A", 90},
	{"A", 180},
	{"A", 90},
	{"A", 90},
	{setChooseCupState, 0},
}``

into 

``local advanceToCharacterSelectSegment = {
	{"none", 70},
	{"A", 300},
	{"A", 50},
	{"A", 75},
	{"A", 400},
	{"down", 25},
	{"A", 90},
	{"A", 180},
	{"A", 90},
	{"A", 90},
	{setChooseCupState, 0},
}``

Note the extra 70 frames to let the game buffer in the extended load or transition time. Not sure if this effects code elsewhere but seems to be fine. 


However, this once again leads to an issue. When attempting to play the ghost using the live replay gecko, it gets stuck on "race this ghost" after viewing the replay. Notably my ghost disappears and potentially even the custom track and it is then replaced by the original Nintendo easy ghost? Will keep trying to fix but no ideas as to what causes this. It seems to be something to do with the "navigateToCompareGhost" function or the local "advLiveReplaySoloTimeTrialSegment" is not being called.

**Comment by RockSaltWA** [comment]
Ok turns out that if you just add an a press to the local for solo TTs before the up press for 96 frames it works. Now however I am trying to edit the gecko codes because it turns out you can't? Whenever the .bat it ran to record the ghost, the gecko files get rewritten. I am attempting to add the BRSAR Patcher because right now the music will randomly turn off in the middle of the run. However, whenever I edit the RMCE01.ini file in dolphin>user>gamesettings it is immediately overwritten upon launching the .bat. I was hoping there is some way to fix this because otherwise the audio just will not completely play. Here's the gecko code as well: 

$BRSAR Patcher (Melg???)
C20912B0 00000002
3FE07FFF 63FFFFFF
93FD0074 00000000

If I had to guess you compiled it into the .exe so that people can't edit out the "Recorded by Auto TT Recorder" message, which makes a lot of sense. Would you think it's possible to push a hotfix patch with that code above included in the gecko code list?

**Comment by RockSaltWA** [comment]
So I told myself I was going to sleep but couldn't, so I instead just ended up looking through the source code. 

I think the Gecko codes are rewrote through the template ini in the data folder??? It seems to have fixed that issue once I rewrote that ini but was a little surprised as there really is no indication for that.

**Comment by luckytyphlosion** [comment]
> Ok turns out that if you just add an a press to the local for solo TTs before the up press for 96 frames it works. Now however I am trying to edit the gecko codes because it turns out you can't? Whenever the .bat it ran to record the ghost, the gecko files get rewritten. I am attempting to add the BRSAR Patcher because right now the music will randomly turn off in the middle of the run. However, whenever I edit the RMCE01.ini file in dolphin>user>gamesettings it is immediately overwritten upon launching the .bat. I was hoping there is some way to fix this because otherwise the audio just will not completely play. Here's the gecko code as well:
> 
> $BRSAR Patcher (Melg???) C20912B0 00000002 3FE07FFF 63FFFFFF 93FD0074 00000000
> 
> If I had to guess you compiled it into the .exe so that people can't edit out the "Recorded by Auto TT Recorder" message, which makes a lot of sense. Would you think it's possible to push a hotfix patch with that code above included in the gecko code list?

you can, just add `ending-message:`

**Comment by luckytyphlosion** [comment]
I don't pay attention to the issue page here so contact me on discord at luckytyphlosion#1166

**Comment by luckytyphlosion** [comment]
The fix was done a while ago but loading times causing script desyncs hopefully should be fixed.
